//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartUser
    {
        public int ID { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> bookid { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
