//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public int ID { get; set; }
        public int orderid { get; set; }
        public int bookid { get; set; }
        public int userid { get; set; }
        public double price { get; set; }
        public int pricesale { get; set; }
        public int quantity { get; set; }
        public double amount { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
    }
}
