//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreMVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int ID { get; set; }
        public int topid { get; set; }
        public string title { get; set; }
        public string slug { get; set; }
        public string detail { get; set; }
        public string img { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public int status { get; set; }
    
        public virtual Topic Topic { get; set; }
    }
}
